name: Electron UI Tests

on: 
  workflow_dispatch: 

jobs:
  electron-ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: List files project
        run: ls -l

     
  
